name: Bug Report
description: Create a report to help improving this project.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Before raising an issue, please search for existing ones to avoid creating duplicates.
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: device-info
    attributes:
      label: Device info
      description: If possible, please provide info about the device where the issue was found.
      placeholder: Desktop/Mobile Model, Operating System, Browser, along with their versions.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
